# Generated by Django 3.2.16 on 2022-12-20 09:51

from django.db import migrations, models
import django.db.models.deletion
import vote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('teample', 'Teample'), ('finble', 'Finble'), ('diametes', 'diaMEtes'), ('recipeasy', 'recipeasy'), ('prefolio', 'Pre:folio')], max_length=20)),
                ('description', models.CharField(default=None, max_length=200)),
                ('vote_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('part', models.CharField(choices=[('plan', 'Plan'), ('design', 'Design'), ('back', 'Back-end'), ('front', 'Front-end')], max_length=10)),
                ('vote_num', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.team')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('part', models.CharField(choices=[('plan', 'Plan'), ('design', 'Design'), ('back', 'Back-end'), ('front', 'Front-end')], max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('part_voted', models.BooleanField(default=False)),
                ('demo_voted', models.BooleanField(default=False)),
                ('vote_num', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.team')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', vote.models.UserManager()),
            ],
        ),
    ]
