# Generated by Django 3.2.16 on 2022-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vote_num',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='part',
            field=models.CharField(choices=[('front', 'Front-end'), ('design', 'Design'), ('back', 'Back-end'), ('plan', 'Plan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('teample', 'Teample'), ('recipeasy', 'recipeasy'), ('finble', 'Finble'), ('prefolio', 'Pre:folio'), ('diametes', 'diaMEtes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.CharField(choices=[('front', 'Front-end'), ('design', 'Design'), ('back', 'Back-end'), ('plan', 'Plan')], max_length=10),
        ),
    ]
